### ISSUE TITLE
Animation is missing

### ISSUE THREAD

**Issue by RahulScripted** [RealisticCoder/Responsive-Landing-Page-Website#3]
I think we should provide some animation here
![Screenshot 2024-10-12 124512](https://github.com/user-attachments/assets/9853964b-06bb-4db3-b736-654c2eca5df0)

**Comment by pranav07-git** [comment]
Ya Maybe you can add a animation here using JS.

**Comment by RahulScripted** [comment]
Yes, I'll be added scroll reveal animation. Can you add some labels like gscoc-extd hacktoberfest2024 or related labels to it

**Comment by pranav07-git** [comment]
Yes , Sure!!

**Comment by pranavraj1720** [comment]
Btw how you found my repository!! Let's Chat
My Instagram: instagram.com/__pranav.17

**Comment by RahulScripted** [comment]
I found your repo while exploring more 😆
